version: '3.1'

services:
  database:
    image: postges:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: animals
    ports:
      - 5432:5432